<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>source.gruescript</string>

        <key>fileTypes</key>
        <array>
            <string>gru</string>
        </array>

        <key>name</key>
        <string>Gruescript</string>

        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>\b(game|room|thing|proc|rule|verb|setverb|var|tagdesc)\b</string>
                <key>name</key>
                <string>keyword.other.block.gruescript</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(author|version|id|person|intro|name|desc|verbs|cverbs|loc|dir|tags|examine|wait|conversation|show_title|instructions|display|prompt|prop|pronoun)\b</string>
                <key>name</key>
                <string>keyword.other.property.gruescript</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(north|northeast|east|southeast|south|southwest|west|northwest|up|down|in|out|fore|aft|port|starboard)\b</string>
                <key>name</key>
                <string>keyword.other.direction.gruescript</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(held|carried|worn|inscope|visible|here|at|thingat|near|eq|is|gt|lt|has|hasany|hasall|taghere|isthing|isroom|chance|try|js|!held|!carried|!inscope|!visible|!here|!at|!thingat|!near|!chance|!eq|!is|!gt|!lt|!has|!taghere|!isthing|!isroom|!try|!js)\b</string>
                <key>name</key>
                <string>keyword.other.assertion.gruescript</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(start|portable|lightsource|wearable|worn|alive|male|female|nonbinary|plural|proper_name|dark|quiet|list_last|cantsee|score|maxscore|maxinv|inv|on|off|things|rooms|tagged|dirs|these|intransitive)\b</string>
                <key>name</key>
                <string>keyword.other.specialtag.gruescript</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(all|select|sequence|!all|!select|!sequence)\b</string>
                <key>name</key>
                <string>keyword.other.iterator.gruescript</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(say|sayat|write|assign|freeze|add|hide|bring|give|carry|wear|unwear|unhold|swap|die|tag|untag|tagroom|untagroom|put|putnear|goto|open|close|random|count|pick|continue|run|log)\b</string>
                <key>name</key>
                <string>keyword.other.command.gruescript</string>
            </dict>
            <dict>
				<key>match</key>
				<string>\b(:)\b</string>
				<key>name</key>
				<string>keyword.operator.gruescript</string>
			</dict>
            <dict>
				<key>match</key>
				<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
				<key>name</key>
				<string>constant.numeric.js</string>
			</dict>
            <dict>
			<key>begin</key>
			<string>(/# )</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.begin.gruescript</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>comment.block.gruescript</string>
			<key>end</key>
			<string>( /)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.end.gruescript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.comment.block.gruescript</string>
		</dict>
        <dict>
			<key>match</key>
			<string>("[^"]*")</string>
			<key>name</key>
			<string>string.quoted.double.gruescript</string>
		</dict>
        <dict>
			<key>match</key>
			<string>\$\b([A-Za-z_][A-Za-z0-9_]*)\b</string>
			<key>name</key>
			<string>variable.parameter.gruescript</string>
		</dict>               
        </array>
        <key>uuid</key>
        <string>bd8b6f0e-6556-4441-9d9e-cebba0cd37ad</string>
    </dict>
</plist>